### ISSUE TITLE
[TODO] チュートリアル作成

### ISSUE THREAD

**Issue by NePonpon** [TUSB/TheUnusualSkyBlock#158]
### 重要度

今すぐ

### このTODOはこのTUSB Versionに影響が出る

v13α

## 何故必要なのか?
1. 進捗によるチュートリアルでは足りない。わからない。
2. 実践的なチュートリアルが欲しい
3.
4.

## 何故必要なのか
1. v13αから増えた要素が説明されない。
2. 今回からv13を体験するプレイヤーは何もわからなくなる。
3.

  

## 何故この重要度なのか
1. ワールドとの連携が必須なためリリース後の制作が難しい
2. 
3. 

## いつまで対応が必要か
1. v13α2配布まで
2. 
3.

**Comment by NePonpon** [comment]
* 場所
  デバッグルームの一角に簡易的なエリアを作成。
  エリア表示は削除、チュートリアル用のタイトル表示が必要
* 行き来の方法
  未定
* チュートリアルの流れ
  チュートリアルエリアに入ったプレイヤーは通常プレイ環境とは切り離される。
  チュートリアルのときはチュートリアル用に職業レベルやスキル習得状態が用意される。

`tutorial_alpha`空間にチュートリアル用のファイルを配置する。
1チュートリアルに対して1フォルダを用意する。
フォルダ名は進捗チュートリアルのように連番ではなく簡易的な名前を付ける。
tick処理はmain:tickの最初から分岐する。
各チュートリアルファイルの中のfunctionを実行することで1つのチュートリアルが完結するようにする。

**Comment by NePonpon** [comment]
- [ ] ステータスログと出現方法について
  備考
  規模：最小(看板のみ)
- [ ] 進捗(簡易チュートリアル)について
  備考
  規模：最小(看板のみ)
- [ ] 死亡時、寝る時際にログに出現する【TIPS】について
  備考
  規模：小
  ベット、スケルトンスキンヘッド設置(死をイメージ)
- [ ] MPについて(経験値バー)
  備考
  規模：最小
  看板にエーテルのアイコンほしくない？
- [ ] 特殊な状態異常について
  備考
  規模：最小
  看板をクリックすると各種属性弾が上空に放たれるギミックとかどうだろ？
- [ ] 空腹デバフ状態だとMPが増えないことについて
  規模：最小
  空腹アイコンほしくない？
- [ ] ネザースター(経験値)とLvUPについて
  規模：小
  アイテムのネザースターが浮遊している(取得不可)
  ディスプレイ化の方がよい？
- [ ] 職業について(アイコン説明)
  規模：最小
  看板に各種職業アイコンが表示されている
- [ ] 職業スキルについて
  規模：中
  クリックすると近くのプレイヤーに１つ人参棒(エリアを跨ぐと没収されるタイプ)を取得させ、
  以下の３点の画像を用意(解像度128x128以内)
  ３点の画像をアイテムディスプレイで表示し、看板をクリックする毎に切り替わりつつ
  説明ログが変わるようなものを作る。
  1. ステータスログを発生させ、カーソルがステータスログのスキルに乗っている
  2. スキルログにおいて共通のスキルログを開きクリックしている様子
  3. アナライズを人参棒に付与し、目標にアナライズを実行している様子
- [ ] TUSBメモリーについて
  規模：最小
  TUSB宣伝チラシをプレイヤーに渡してTUSBMがこういうものだと理解させる。
- [ ] バーストゲージとバーストスキルの作動の仕方について
  規模：最小
  やはりバーストゲージのアイコン必要では？
- [ ] スキル設定についての手順について
  上の職業スキルについてを参照。
- [ ] 現在の職業スキルと共通のスキルの出し方について
  上の職業スキルについてを参照？
- [ ] エンドポータルフレームにエンダーアイをのはめた際の達成率の上昇について
  規模：小
  ディスプレイ化。v12のような構成(今度は最初からはまっている)
- [ ] adv化するアイテムについて(ツルハシ、ツタ、松明、エンダーアイ)
  規模：小
  ディスプレイ化
- [ ] 難易度(現状カジュアルのみ)について
  規模：最小
  難易度についての説明。
- [ ] 自然湧きのMOBについて
  規模：最小
  自然湧きが改造MOBオンリーですよーという宣言。
  対策がなければ危険であるということを伝える。
- [ ] スポナーについて
  規模：中
  看板がクリックされる毎にピッケルのディスプレイモーションが連動し、
  数値が減っていき、HPが0になると破壊されるといったものが見本として使用されている。
  またスポナーがないとき、看板をクリックすると初期化される。
- [ ] 魔石について
  規模：小
  クリックする毎に炎、氷、雷...とTier1の魔石がランダムで切り替わるアイテムディスプレイ。
- [ ] エンチャント台について
- [ ] 金床について
- [ ] 砥石について
- [ ] ビーコンについて
- [ ] TNTの即時起爆について
- [ ] 草ブロックと羊の湧きの関係について
- [ ] 釣りとバイオームの関係性について
- [ ] エリアについて
- [ ] 通常のネザーやエンドについて

**Comment by anminmakura** [comment]
TUSBメモリーについて
```
TUSBM（Temporary Use Skill Bio Memory）は、職業スキルとは異なるスキルです。
どの職業でもMPを消費せず、デバフによる邪魔を無視するスキルを使用できます。
アイテムに最初から付与されており、自身で付与はできません。
```

TUSBメモリーの注意点
```
TUSBMは職業スキルによる上書きが出来ません。
アイテムの使用回数が0になると、耐久値に関わらずアイテムは破壊されます。
TUSBMには職業スキルにはない未知のスキルが付与されていることがあります。
スキルの作動間隔や作動条件も職業スキルとは異なる場合があります。
```
_ご自由にお取りください。って看板があって、
クリックするとTUSB宣伝チラシが手に入ると面白そう？_

adv化するアイテムについて

```
この世界において特定のエリアに
特定のアイテム(ツルハシ、ツタ、松明、エンダーアイ)を
メインハンドに持つことでアドベンチャーエリアに適用する場合があります。
```

自然湧きのモブについて
```
この世界では、各エリアごとに異なる生態系が広がっています。
平和な場所は限られており、混沌とした環境に適応できた強者だけが生き残りました。
一部の場所（通常世界の初期地点周辺や飛空島など）では自然湧きがないため、比較的安全です。
```

モブのLvについて
```
モブの名前の右に表示されているLv値はモブの強さの指標を表しています。
基本的にはLvが高ければ強くなりモブのステータス等に影響を与えます。
※モブのステータスについては進捗に書いています
```
※tutorial14を参照。

ディスコードのまとめ。

**Comment by NePonpon** [comment]
チュートリアルフォーマット
```
[チュートリアル：%1$s] <- チュートリアルの名前、太字
\nで改行してから本文
```

**Comment by NePonpon** [comment]
チュートリアルのエリアでのみ所持可能なアイテムに付与するNBT
`tutorial_item:true`
退出時にclearする

**Comment by NePonpon** [comment]
# 実装されたチュートリアル

* 進捗画面
* チャットログの使い方
* Advエリアで使えるアイテム
* TUSBの難易度
* 変異したエンチャントテーブル
* 魔石の出現
* メニュー
* サバイバルとアドベンチャー
* 草ブロックとヒツジ
* 変異した砥石
* 達成率
* 職業の経験値とレベル
* 職業
* 変異した金床
* Mobのレベル
* MP
* 各種の生態系
* ネザーとエンドは？
* バーストブレイクその１
* バーストブレイクその２
* スキルの設定
* スキルショートカットその１
* スキルショートカットその２
* スキルの確認
* スキルを使う
* スポナー
* TIPS
* TNTの爆発
* 特殊デバフ/火だるま
* 特殊デバフ/混乱
* 特殊デバフ/呪詛
* 特殊デバフ/衰弱
* 特殊デバフ/死の宣告
* 特殊デバフ/凍結
* 特殊デバフ/ペイル
* 特殊デバフ/麻痺
* 特殊デバフ/トント
* 特殊デバフ/病気
* TUSBメモリー
* TUSBメモリーの注意点
* 特殊な床
* カスタム床
* 酸床
* 即死床
* 落とし床
* 矢印床

46個

**Comment by anminmakura** [comment]
順番を定義

# 実装されたチュートリアル

## 1,基本操作編
1-1, 進捗画面
1-2, チャットログの使い方
1-3, メニュー
1-4, TIPS

## 2,マイクラの基礎知識編
2-1, サバイバルとアドベンチャー
2-2, 草ブロックとヒツジ
2-3, ネザーとエンドは？
2-4, TNTの爆発

## 3,TUSBの基礎知識編
3-1, TUSBの難易度
3-2, 達成率
3-3, Advエリアで使えるアイテム

## 4,魔石システム編
4-1, 魔石の出現
4-2, 変異したエンチャントテーブル
4-3, 変異した金床
4-4, 変異した砥石

## 5,特殊なデバフ編
5-1, 特殊デバフ/火だるま
5-2, 特殊デバフ/凍結
5-3, 特殊デバフ/麻痺
5-4, 特殊デバフ/混乱
5-5, 特殊デバフ/呪詛
5-6, 特殊デバフ/病気
5-7, 特殊デバフ/トント
5-8, 特殊デバフ/衰弱
5-9, 特殊デバフ/死の宣告
5-10, 特殊デバフ/ペイル

## 6,特殊な床編
6-1, 特殊な床
6-2, 矢印床
6-3, 落とし床
6-4, 酸床
6-5, 即死床
6-6, カスタム床

## 7,モブシステム編
7-1, 各種の生態系
7-2, Mobのレベル
7-3, スポナー

## 8,職業とスキル編
8-1, 職業
8-2, 職業の経験値とレベル
8-3, MP
8-4, スキルの確認
8-5, スキルの設定
8-6, スキルを使う
8-7, スキルショートカットその１
8-8, スキルショートカットその２
8-9, バーストブレイクその１
8-10, バーストブレイクその２
8-11, TUSBメモリー
8-12, TUSBメモリーの注意点

**Comment by NePonpon** [comment]
チュートリアルエリアのシステムをすべて実装できたので終了
* 看板クリック時のチュートリアルメッセージ
* チュートリアルエリア入退場のシステム
* チュートリアルエリアの地形、建築
